### ISSUE TITLE
APK size too big

### ISSUE THREAD

**Issue by davidaik** [imgly/imgly-sdk-android#4]
My app without imgly-is ~2.5 MB. With imgly it is ~23MB.

I extracted my apk and saw that the bloat is due to contents of drawable-nodpi-v4.

It contains 62 LUT images for a total of 8.13 MB. I understand that these files are needed for the filters. However, there are two other files, photo.jpg (1.30MB), and photo_port.png (5.62 MB), for a total of 6.92 MB. Both are images of some mountain.

These files, photo.jpg and photo_port.png, I imagine, are completely useless in my app? How to prevent these files from being included in my apk?

**Comment by svendvd** [comment]
Sorry for that, we will remove the files in the next patch version. We used it for testing and it should not be in production.

**Comment by davidaik** [comment]
Thanks, svendvd.
